### ISSUE TITLE
Mismatched argument in graph_bfs

### ISSUE THREAD

**Issue by gnat79** [Bears-R-Us/arkouda-njit#16]
Calling graph_bfs raises a NameError:
```
NameError: name 'RCMFlag' is not defined
```
Looking at the code it's on line 436 of graph.py where the argument passed in is called `rcm_flag` but the line needs to be updated to use that name instead of `"RCMFlag": RCMFlag` in the `args` dictionary.

**Comment by zhihuidu** [comment]
Thanks and it has been fixed.Zhihui Sent from Mail for Windows From: NathanielSent: Friday, December 2, 2022 9:25 AMTo: Bears-R-Us/arkouda-njitCc: SubscribedSubject: [Bears-R-Us/arkouda-njit] Mismatched argument in graph_bfs (Issue #16) Calling graph_bfs raises a NameError:NameError: name 'RCMFlag' is not definedLooking at the code it's on line 436 of graph.py where the argument passed in is called rcm_flag but the line needs to be updated to use that name instead of "RCMFlag": RCMFlag in the args dictionary.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
